version: '3'

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    command:
      - /bin/sh
      - -c
      - |
        apt-get -y install git
        git config --global user.name "Suhaimi Bin Roslan"
        git config --global user.email 2001684@sit.singaporetech.edu.sg
  
  webapp:
    container_name: webapp
    build: ./webapp
    ports:
      - "80:80"

volumes:
  jenkins_data:
    driver: local